"""Add cascade delete from User to MentorAssignment

Revision ID: 679c84181633
Revises: a7430f61bfc8
Create Date: 2025-09-10 23:03:42.234275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '679c84181633'
down_revision = 'a7430f61bfc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classes_is_archived'), ['is_archived'], unique=False)

    with op.batch_alter_table('mentee_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('mentee_profiles_reg_num_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_mentee_profiles_reg_num'))
        batch_op.create_index(batch_op.f('ix_mentee_profiles_reg_num'), ['reg_num'], unique=True)

    with op.batch_alter_table('mentor_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('mentor_assignments_original_mentor_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('mentor_assignments_mentor_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['original_mentor_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['mentor_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentor_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('mentor_assignments_mentor_id_fkey'), 'users', ['mentor_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('mentor_assignments_original_mentor_id_fkey'), 'users', ['original_mentor_id'], ['id'])

    with op.batch_alter_table('mentee_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mentee_profiles_reg_num'))
        batch_op.create_index(batch_op.f('ix_mentee_profiles_reg_num'), ['reg_num'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('mentee_profiles_reg_num_key'), ['reg_num'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classes_is_archived'))

    # ### end Alembic commands ###
