"""Add full cascade delete for users, classes, and assignments

Revision ID: 8fef205bc98a
Revises: 679c84181633
Create Date: 2025-09-10 23:10:40.775079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fef205bc98a'
down_revision = '679c84181633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_semester_mark_details', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('academic_semester_mark_details_mentee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['mentee_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('attendance_records_mentee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['mentee_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('awards_and_achievements', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('awards_and_achievements_mentee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['mentee_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('batches_class_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'classes', ['class_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('cocurricular_activity_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('cocurricular_activity_records_mentee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['mentee_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('extracurricular_activity_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('extracurricular_activity_records_mentee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['mentee_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('honors_minor_marks_details', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('honors_minor_marks_details_mentee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['mentee_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('internship_information', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('internship_information_mentee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['mentee_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('leave_requests_mentee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['mentee_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('mentee_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('mentee_profiles_class_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('mentee_profiles_batch_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'classes', ['class_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'batches', ['batch_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('mentor_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('mentor_assignments_batch_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('mentor_assignments_original_mentor_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['original_mentor_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'batches', ['batch_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('mentor_meeting_details', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('mentor_meeting_details_mentee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['mentee_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('notifications_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('placement_information', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('placement_information_mentee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['mentee_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('research_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('research_records_mentee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['mentee_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('sessions_mentor_assignment_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'mentor_assignments', ['mentor_assignment_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('sessions_mentor_assignment_id_fkey'), 'mentor_assignments', ['mentor_assignment_id'], ['id'])

    with op.batch_alter_table('research_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('research_records_mentee_id_fkey'), 'users', ['mentee_id'], ['id'])

    with op.batch_alter_table('placement_information', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('placement_information_mentee_id_fkey'), 'users', ['mentee_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notifications_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('mentor_meeting_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('mentor_meeting_details_mentee_id_fkey'), 'users', ['mentee_id'], ['id'])

    with op.batch_alter_table('mentor_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('mentor_assignments_original_mentor_id_fkey'), 'users', ['original_mentor_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('mentor_assignments_batch_id_fkey'), 'batches', ['batch_id'], ['id'])

    with op.batch_alter_table('mentee_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('mentee_profiles_batch_id_fkey'), 'batches', ['batch_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('mentee_profiles_class_id_fkey'), 'classes', ['class_id'], ['id'])

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('leave_requests_mentee_id_fkey'), 'users', ['mentee_id'], ['id'])

    with op.batch_alter_table('internship_information', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('internship_information_mentee_id_fkey'), 'users', ['mentee_id'], ['id'])

    with op.batch_alter_table('honors_minor_marks_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('honors_minor_marks_details_mentee_id_fkey'), 'users', ['mentee_id'], ['id'])

    with op.batch_alter_table('extracurricular_activity_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('extracurricular_activity_records_mentee_id_fkey'), 'users', ['mentee_id'], ['id'])

    with op.batch_alter_table('cocurricular_activity_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cocurricular_activity_records_mentee_id_fkey'), 'users', ['mentee_id'], ['id'])

    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('batches_class_id_fkey'), 'classes', ['class_id'], ['id'])

    with op.batch_alter_table('awards_and_achievements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('awards_and_achievements_mentee_id_fkey'), 'users', ['mentee_id'], ['id'])

    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('attendance_records_mentee_id_fkey'), 'users', ['mentee_id'], ['id'])

    with op.batch_alter_table('academic_semester_mark_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('academic_semester_mark_details_mentee_id_fkey'), 'users', ['mentee_id'], ['id'])

    # ### end Alembic commands ###
