"""Initial migration

Revision ID: a7430f61bfc8
Revises: 
Create Date: 2025-09-10 21:21:45.990063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7430f61bfc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('profile_picture', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('admin_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batches_is_active'), ['is_active'], unique=False)

    op.create_table('mentor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('cabin_block', sa.String(length=50), nullable=True),
    sa.Column('cabin_floor', sa.String(length=50), nullable=True),
    sa.Column('cabin_number', sa.String(length=50), nullable=True),
    sa.Column('profile_complete', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_timestamp'), ['timestamp'], unique=False)

    op.create_table('mentee_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reg_num', sa.String(length=50), nullable=False),
    sa.Column('admission_number', sa.String(length=50), nullable=True),
    sa.Column('year_of_joining', sa.Integer(), nullable=True),
    sa.Column('programme', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('residential_phone', sa.String(length=20), nullable=True),
    sa.Column('personal_cell', sa.String(length=20), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('father_name', sa.String(length=100), nullable=True),
    sa.Column('father_education', sa.String(length=100), nullable=True),
    sa.Column('father_occupation', sa.String(length=100), nullable=True),
    sa.Column('father_phone', sa.String(length=20), nullable=True),
    sa.Column('father_email', sa.String(length=120), nullable=True),
    sa.Column('mother_name', sa.String(length=100), nullable=True),
    sa.Column('mother_education', sa.String(length=100), nullable=True),
    sa.Column('mother_occupation', sa.String(length=100), nullable=True),
    sa.Column('mother_phone', sa.String(length=20), nullable=True),
    sa.Column('mother_email', sa.String(length=120), nullable=True),
    sa.Column('family_income', sa.String(length=50), nullable=True),
    sa.Column('siblings', sa.Integer(), nullable=True),
    sa.Column('local_residence_type', sa.String(length=50), nullable=True),
    sa.Column('guardian_name', sa.String(length=100), nullable=True),
    sa.Column('guardian_relationship', sa.String(length=100), nullable=True),
    sa.Column('hostel_location', sa.String(length=50), nullable=True),
    sa.Column('hostel_name', sa.String(length=100), nullable=True),
    sa.Column('pg_owner_name', sa.String(length=100), nullable=True),
    sa.Column('pg_owner_mobile', sa.String(length=20), nullable=True),
    sa.Column('residence_address', sa.Text(), nullable=True),
    sa.Column('semester', sa.String(length=50), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('archive_label', sa.String(length=100), nullable=True),
    sa.Column('profile_complete', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reg_num'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('mentee_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mentee_profiles_archive_label'), ['archive_label'], unique=False)
        batch_op.create_index(batch_op.f('ix_mentee_profiles_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_mentee_profiles_reg_num'), ['reg_num'], unique=False)

    op.create_table('mentor_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('is_temporary', sa.Boolean(), nullable=True),
    sa.Column('temp_start_date', sa.Date(), nullable=True),
    sa.Column('temp_end_date', sa.Date(), nullable=True),
    sa.Column('original_mentor_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['original_mentor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mentor_id', 'batch_id', 'is_active', name='_mentor_batch_active_uc')
    )
    with op.batch_alter_table('mentor_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mentor_assignments_is_active'), ['is_active'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentor_assignment_id', sa.Integer(), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('actual_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mentor_assignment_id'], ['mentor_assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_start_time'), ['start_time'], unique=False)

    op.create_table('academic_semester_mark_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentee_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=50), nullable=True),
    sa.Column('subject_code_name', sa.String(length=255), nullable=True),
    sa.Column('cia_1', sa.Float(), nullable=True),
    sa.Column('cia_2', sa.Float(), nullable=True),
    sa.Column('cia_3', sa.Float(), nullable=True),
    sa.Column('overall_cia', sa.Float(), nullable=True),
    sa.Column('ese_attempt_1', sa.Float(), nullable=True),
    sa.Column('ese_attempt_2', sa.Float(), nullable=True),
    sa.Column('ese_attempt_3', sa.Float(), nullable=True),
    sa.Column('ese_attempt_4', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('attendance_percentage', sa.Float(), nullable=True),
    sa.Column('course_acceleration_deceleration', sa.String(length=50), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('cgpa', sa.Float(), nullable=True),
    sa.Column('suggestions_by_mentor', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['mentee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('mentee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['mentee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('awards_and_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentee_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('award_achievement_name', sa.String(length=255), nullable=True),
    sa.Column('award_achievement_type', sa.String(length=100), nullable=True),
    sa.Column('conducted_by', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['mentee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cocurricular_activity_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentee_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('activity_name', sa.String(length=255), nullable=True),
    sa.Column('activity_type', sa.String(length=100), nullable=True),
    sa.Column('conducted_by', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['mentee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracurricular_activity_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentee_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('activity_name', sa.String(length=255), nullable=True),
    sa.Column('activity_type', sa.String(length=100), nullable=True),
    sa.Column('conducted_by', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['mentee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('honors_minor_marks_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentee_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=50), nullable=True),
    sa.Column('subject_code_name', sa.String(length=255), nullable=True),
    sa.Column('cia_1', sa.Float(), nullable=True),
    sa.Column('cia_2', sa.Float(), nullable=True),
    sa.Column('cia_3', sa.Float(), nullable=True),
    sa.Column('overall_cia', sa.Float(), nullable=True),
    sa.Column('ese_attempt_1', sa.Float(), nullable=True),
    sa.Column('ese_attempt_2', sa.Float(), nullable=True),
    sa.Column('ese_attempt_3', sa.Float(), nullable=True),
    sa.Column('ese_attempt_4', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('attendance_percentage', sa.Float(), nullable=True),
    sa.Column('course_acceleration_deceleration', sa.String(length=50), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('cgpa', sa.Float(), nullable=True),
    sa.Column('suggestions_by_mentor', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['mentee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('internship_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentee_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('duration_from', sa.Date(), nullable=True),
    sa.Column('duration_to', sa.Date(), nullable=True),
    sa.Column('sem', sa.String(length=50), nullable=True),
    sa.Column('technology_domain', sa.String(length=255), nullable=True),
    sa.Column('internship_project_details', sa.Text(), nullable=True),
    sa.Column('company_location', sa.String(length=255), nullable=True),
    sa.Column('internship_status', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['mentee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('mentee_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mentee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_requests_status'), ['status'], unique=False)

    op.create_table('mentor_meeting_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('mentee_id', sa.Integer(), nullable=False),
    sa.Column('points_discussed', sa.Text(), nullable=True),
    sa.Column('remarks_given', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['mentee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('placement_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentee_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_location', sa.String(length=255), nullable=True),
    sa.Column('interview_date', sa.Date(), nullable=True),
    sa.Column('rounds_attended', sa.Integer(), nullable=True),
    sa.Column('internship_provided', sa.Boolean(), nullable=True),
    sa.Column('annual_ctc', sa.Float(), nullable=True),
    sa.Column('stipend_amount', sa.Float(), nullable=True),
    sa.Column('interview_status', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['mentee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentee_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('publication_name', sa.String(length=255), nullable=True),
    sa.Column('identifier_number', sa.String(length=100), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('publication_type', sa.String(length=100), nullable=True),
    sa.Column('publication_status', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['mentee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('research_records')
    op.drop_table('placement_information')
    op.drop_table('mentor_meeting_details')
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_requests_status'))

    op.drop_table('leave_requests')
    op.drop_table('internship_information')
    op.drop_table('honors_minor_marks_details')
    op.drop_table('extracurricular_activity_records')
    op.drop_table('cocurricular_activity_records')
    op.drop_table('awards_and_achievements')
    op.drop_table('attendance_records')
    op.drop_table('academic_semester_mark_details')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_start_time'))

    op.drop_table('sessions')
    with op.batch_alter_table('mentor_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mentor_assignments_is_active'))

    op.drop_table('mentor_assignments')
    with op.batch_alter_table('mentee_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mentee_profiles_reg_num'))
        batch_op.drop_index(batch_op.f('ix_mentee_profiles_is_active'))
        batch_op.drop_index(batch_op.f('ix_mentee_profiles_archive_label'))

    op.drop_table('mentee_profiles')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_timestamp'))

    op.drop_table('notifications')
    op.drop_table('mentor_profiles')
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batches_is_active'))

    op.drop_table('batches')
    op.drop_table('admin_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('classes')
    # ### end Alembic commands ###